version: "3"
services:

  keydb:
    image: eqalpha/keydb:x86_64_v5.3.3
    container_name: keydb
    # command: keydb-server /etc/keydb/redis.conf --server-threads 2 --active-replica yes --replicaof 192.168.1.1 6379
    # command: keydb-server /etc/keydb/redis.conf --server-threads 2 --active-replica yes --replicaof 192.168.1.2 6379
    command: keydb-server /etc/keydb/redis.conf --server-threads 2
    volumes:
      - ./docker-conf/redis.conf:/etc/keydb/redis.conf
      - data:/data
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - integracao

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - integracao

  jaeger:
    image: jaegertracing/jaeger:2.2.0
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OpenTelemetry gRPC
      - "4318:4318"   # OpenTelemetry HTTP
      - "5778:5778"   # Configuration service
      - "9411:9411"   # Zipkin compatibility
    restart: unless-stopped
    networks:
      - integracao

networks:
  integracao:
    driver: bridge

volumes:
  data:
    driver: local

